from entidades.car import Car
from entidades.employee import Employee
from entidades.driver import Driver
from entidades.reserve_driver import ReserveDriver
from entidades.team_principal import TeamPrincipal
from entidades.mechanic import Mechanic
from entidades.fia import Fia
from entidades.race import Race
from entidades.team import Team
